My first pull request!
jevazquezb/Hello-world pull request #1
Opened 2021-09-14 22:15 UTC by jevazquezb

2021-09-14 23:14 UTC, ZeenatLawal requested changes
Hi @jevazquezb, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-14 23:14 UTC, ZeenatLawal commented on README.md
> +![](https://img.shields.io/badge/Microverse-blueviolet)
- [ ] Your Pull Request should have a descriptive title so it will be easy to tell what changes are inside and a short summary describing introduced changes in more detail. This also makes your project documentation professional.

2021-09-14 23:14 UTC, ZeenatLawal commented on README.md
> +![](https://img.shields.io/badge/Microverse-blueviolet)
- [ ] Your commit messages were descriptive but I would suggest using the verbs without adding the -ing suffix (e.g. fix instead of fixing) to follow best practices.

2021-09-14 23:14 UTC, ZeenatLawal commented on README.md
> +![](https://img.shields.io/badge/Microverse-blueviolet)
- [ ] Your branch should have a name of a feature or action (e.g. 'created_sidebar' or 'added_comments_section' ).

2021-09-15 00:13 UTC, jevazquezb commented
##“Hello Microverse Project” for beginners.

Here we learned how to:

- Create branches, work within and push changes to github.
- Set up linters.
- Ignore files in git by using the .gitignore file
- Edit .html files to write a title
- Edit .css files to style a title
- Create a pull request.

2021-09-15 02:15 UTC, closed without merging